### PR TITLE
readme.md

### PR DESCRIPTION
**Pull request by bumsoft**
- coin.md
Modified file name and content

- README.md
Modified Coin team member's name
Modified path "requirements/codingping"  to "requirements/codingping.md"

### CODE REVIEW

**Review by dev-moonsc — APPROVED** [review]
LGTM

**Review by dev-moonsc — CHANGES_REQUESTED** [review]
your README.md file is not up-to-date, which might cause conflicts with your changes.

**Comment by bumsoft** [comment]
> your README.md file is not up-to-date, which might cause conflicts with your changes.

After merging the previous PR, I updated the branch again and resolved the conflicts. The commit message was automatically generated during that process. So there would be no conflict.

**Review by dev-moonsc — APPROVED** [review]
I understand. LGTM :)

**Review by fkrdud1125 — APPROVED** [review]
LGTM

**Pull request merged**
