### PR TITLE
Playable ships variety: 3 additional ships with different stats, along with items compatibility

### PR DESCRIPTION
**Pull request by brewcoua**
This PR adds 3 new ships, while allowing the possible addition of more in the future.
The ships have set names, sprites, and stats multipliers (shooting interval, bullet speed, movement speed).
They are not yet directly selectable by the user, a feature which will be implemented in the near future through the settings screen.

### CODE REVIEW

**Review by bumsoft — COMMENTED** [review]
Are the stats purchased from the shop applied? I apologize for the inconvenience, but I am unable to check the code at the moment.

**Comment by brewcoua** [comment]
> Are the stats purchased from the shop applied? I apologize for the inconvenience, but I am unable to check the code at the moment.

They are indeed applied, as the ones from the shop are modifying the base stats directly, whereas the ships are multiplying the base stats itselves.

**Review by PIut0 — COMMENTED** [review]
The code looks fine, but I can't see the actual execution results. 😢

**Comment by bumsoft** [comment]
> > Are the stats purchased from the shop applied? I apologize for the inconvenience, but I am unable to check the code at the moment.
> 
> They are indeed applied, as the ones from the shop are modifying the base stats directly, whereas the ships are multiplying the base stats itselves.

I just check the code. It looks good :)

**Comment by bumsoft** [comment]
I played by changing the ship myself and there were no problems! (There is an issue with the VoidReaper's stats being too good :))  Please just resolve the conflict .

**Comment by brewcoua** [comment]
> I played by changing the ship myself and there were no problems! (There is an issue with the VoidReaper's stats being too good :)) Please just resolve the conflict .

(I'm thinking of lowering the damage of the bullets once the health is properly implemented :+1:)

**Review by bumsoft — APPROVED** [review]

**Review by bumsoft — CHANGES_REQUESTED** [review]
It seems you need to resolve conflicts again due to a merge from another team.

**Comment by brewcoua** [comment]
> It seems you need to resolve conflicts again due to a merge from another team.

Done!

**Review by bumsoft — APPROVED** [review]

**Review by logpacket — APPROVED** [review]
LGTM :)

**Pull request merged**
