### PR TITLE
docs: Update gamza.md, README.md, creditlist

### PR DESCRIPTION
**Pull request by yeyoungyun**
## **Docs**
- Update docs due to team member changes and our team requirements modification

### CODE REVIEW

**Comment by jinwoo1289** [comment]
LGTM

**Comment by yeyoungyun** [comment]
> LGTM

Plz change the comment to approve

**Review by PIut0 — APPROVED** [review]
LGTM :)

**Review by jinwoo1289 — APPROVED** [review]
LGTM.

**Pull request merged**
