### PR TITLE
feature: add volume controller

### PR DESCRIPTION
**Pull request by yeyoungyun**
### **Feature**
- add volume controller(up&down)

### CODE REVIEW

**Review by PIut0 — CHANGES_REQUESTED** [review]
please add a `getVolume` method.

**Comment by yeyoungyun** [comment]
Added that method.

**Comment by yeyoungyun** [comment]
> please add a `getVolume` method.

Added that method.

**Review by PIut0 — APPROVED** [review]
LGTM :+1:

**Review by bumsoft — APPROVED** [review]
LGTM

**Pull request merged**
