### PR TITLE
Fix GameScreen Height Issue and Modify Line-bomb item

### PR DESCRIPTION
**Pull request by dev-moonsc**
## `GameScreen` Height Issue
- Fixed an issue that `ship` and `web` escape the `GameScreen` in certain environment.
- It was temporary resolved in #75 by simply adjusting the initial y-position of the `ship` and `web`, but it led to issues with the margin between the `ship/web` and the bottom of the `GameScreen` increasing in certain environments, causing it to overlap the `Barrier`
- So, we resolved it by modifying `Frame.java`. We assumed that `Insets.bottom` should be subtracted instead of added when determining height, and confirmed that there is no problem in most environments.
- If you find any problems while testing, please tell me by comment.

## Modify `Line-bomb` item
- Modified it to destroy enemies on the bottom row. (as we originally intended.)

### CODE REVIEW

**Comment by brewcoua** [comment]
This still seems to break my game unfortunately. As this might just be an OS-level problem, if this causes any issue, I can simply keep the height change locally while this PR can be merged.
Here's a preview:
[Screencast from 2024-10-17 09-02-57.webm](https://github.com/user-attachments/assets/a9940a13-8f54-49f1-a148-3635213284cc)

**Review by brewcoua — APPROVED** [review]

**Comment by dev-moonsc** [comment]
> This still seems to break my game unfortunately. As this might just be an OS-level problem, if this causes any issue, I can simply keep the height change locally while this PR can be merged. Here's a preview: [Screencast from 2024-10-17 09-02-57.webm](https://github.com/user-attachments/assets/a9940a13-8f54-49f1-a148-3635213284cc)

Could I know which OS you use?

**Comment by brewcoua** [comment]
> > This still seems to break my game unfortunately. As this might just be an OS-level problem, if this causes any issue, I can simply keep the height change locally while this PR can be merged. Here's a preview: [Screencast from 2024-10-17 09-02-57.webm](https://github.com/user-attachments/assets/a9940a13-8f54-49f1-a148-3635213284cc)
> 
> Could I know which OS you use?

Currently on a standard Ubuntu 24.04 (noble)

**Comment by dev-moonsc** [comment]
> > > This still seems to break my game unfortunately. As this might just be an OS-level problem, if this causes any issue, I can simply keep the height change locally while this PR can be merged. Here's a preview: [Screencast from 2024-10-17 09-02-57.webm](https://github.com/user-attachments/assets/a9940a13-8f54-49f1-a148-3635213284cc)
> > 
> > 
> > Could I know which OS you use?
> 
> Currently on a standard Ubuntu 24.04 (noble)

I see. We'll trying to resolve it. Thanks :)

**Review by fkrdud1125 — APPROVED** [review]
LGTM

**Pull request merged**
